language: swift
osx_image: xcode9.4

script:
  - pod spec lint QueryItemEncoder.podspec
  - fastlane scan --scheme QueryItemEncoder --code_coverage --skip_build
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'QueryItemEncoder'
