language: swift
osx_image: xcode9.4

script:
  - pod spec lint QueryItemEncoder.podspec
  - fastlane scan --code_coverage --scheme QueryItemEncoder
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'QueryItemEncoder'
