language: swift
osx_image: xcode9.4

before_install:
  - pip install codecov

script:
  - pod spec lint QueryItemEncoder.podspec
  - xcodebuild -project QueryItemEncoder.xcodeproj -scheme QueryItemEncoderTests build-for-testing -sdk iphonesimulator
  - xctool -project QueryItemEncoder.xcodeproj -scheme QueryItemEncoderTests run-tests -sdk iphonesimulator

after_success:
  - codecov
