language: swift
osx_image: xcode9.4
xcode_project: QueryItemEncoder.xcodeproj
xcode_scheme: QueryItemEncoderTests

before_install:
  - gem install cocoapods

script:
  - pod spec lint QueryItemEncoder.podspec
