language: swift
osx_image: xcode9.4

before_install:
  - gem install cocoapods
  - brew install xctool

script:
  - pod spec lint QueryItemEncoder.podspec
  - xctool -project QueryItemEncoder.xcodeproj -scheme QueryItemEncoderTests run-tests -sdk iphonesimulator

after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'QueryItemEncoder'
