language: swift
osx_image: xcode9.4

script:
  - pod spec lint QueryItemEncoder.podspec
  - xcodebuild -project QueryItemEncoder.xcodeproj -scheme QueryItemEncoderTests test -sdk iphonesimulator -enableCodeCoverage YES
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'QueryItemEncoder'
